name: 构建Mindoc镜像

on:
  workflow_dispatch:
    inputs:
      tagVersion:
        description: "Cheout tag version"
        required: true
        default: "v2.2-beta.1"
  workflow_call:
    secrets:
      CR_PAT:
        required: true
        description: "github 个人授权Token"
      DOCKERHUB_USERNAME:
        required: true
        description: "dockerhub 用户名称"
      DOCKERHUB_TOKEN:
        required: true
        description: "dockerhub 授权token"

  push:
    branches:
      - master
    paths:
      - "./Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - id: repo_name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository_owner }}

      - name: 构建并推送到Dockerhub和ghcr.io镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            akyakya/mindoc:latest
            ghcr.io/${{ steps.repo_name.outputs.lowercase }}/mindoc:latest
